### ISSUE TITLE
Reorganize Parallel/PipeParallel/Shm domain definitions

### ISSUE THREAD

**Issue by neo-alex** [airbus/scikit-decide#107]
## 🐛 Bug

Today domains.py contains not only domain "templates" (like RLDomain, DeterministicPlanningDomain...) but also some implemented domain utilities (ParallelDomain, PipeParallelDomain, ShmDomain), which creates confusion and some undesired side effects (e.g. they appear in the wrong place in the documentation's code generators by default).

## Expected behavior

Move ParallelDomain, PipeParallelDomain and ShmDomain definitions out of domains.py (e.g. in `utils.py` or a new dedicated module).

**Comment by fteicht** [comment]
I agree, this is an easy fix.
