### ISSUE TITLE
GymDiscreteActionDomain does not discretize Box space correctly

### ISSUE THREAD

**Issue by galleon** [airbus/scikit-decide#175]
## 🐛 Bug

GymDiscreteActionDomain does not discretize Box space correctly

## To Reproduce

Steps to reproduce the behaviour:

1. I have a gym env which define a Box(low=-1, high=1, shape=(2,)) action space
2. When using IW which uses a custom wrapper inheriting from GymDiscreteActionDomain
3. The action space is not properly discretized as the `domain._applicable_actions.get_elements()` contains `[-1., 1.875]`which is not a valid action

## Expected behavior

I expected all generated elements to be in `[-1, 1]^2`

**Comment by nhuet** [comment]
Should be closed as duplicated with #205 which has been solved.

**Comment by fteicht** [comment]
Solved in PR #205
