### ISSUE TITLE
Update RLlib multi-agent environment wrapper

### ISSUE THREAD

**Issue by neo-alex** [airbus/scikit-decide#197]
## 🐛 Bug

The RLlib multi-agent environment wrapper is broken and needs to be updated to the latest API from RLlib in order to work again.

## To Reproduce

1. Select any multi-agent domain (or single-agent one that will be automatically casted)
2. Start solving it with the RLlib multi-agent wrapper

## Expected behavior

The solver should start without error and return a solution.

**Comment by nhuet** [comment]
This is solved by PR #284
