### ISSUE TITLE
EmptySpace should inherit from EnumerableSpace, not from Space

### ISSUE THREAD

**Issue by fteicht** [airbus/scikit-decide#201]
In [core.py](https://github.com/airbus/scikit-decide/blob/da443f54a6154ba05d3316031a3b1d70ef080e37/skdecide/core.py), `EmptySpace` [reimplement](https://github.com/airbus/scikit-decide/blob/da443f54a6154ba05d3316031a3b1d70ef080e37/skdecide/core.py#L139) the asbtract method `get_elements()` which is [declared](https://github.com/airbus/scikit-decide/blob/da443f54a6154ba05d3316031a3b1d70ef080e37/skdecide/core.py#L127) for the first time as an abstract method of `EnumerableSpace`.

However, `EmptySpace` is defined as [inheriting](https://github.com/airbus/scikit-decide/blob/da443f54a6154ba05d3316031a3b1d70ef080e37/skdecide/core.py#L139) from `Space`. The latter declares the abstract method `contains(T)` which is reimplemented in `EnumerableSpace` but not in `EmptySpace`.

As such, the `EmptySpace` class is thus abstract whereas it should not (and I believe it is not the intended behaviour).
The fix consists in making `EmptySpace` inherits from `EnumerableSpace` instead of `Space`. Which makes sense since an empty space is an enumerable space with no element.

**Comment by neo-alex** [comment]
I agree with your comment, but after common discussion it seems that we could even get rid of EmptySpace completely since it is only used once in the library (as a placeholder for temporary code), directly using EnumerableSpace initialized with an empty list instead. I will try to do a PR for that shortly.

**Comment by neo-alex** [comment]
Erratum: actually, EnumerableSpace cannot be initialized with an empty list since it really acts as an abstract class and not an implementation (I got confused with ListSpace), so I ended up following exactly your original suggestion.
