### ISSUE TITLE
RayRLlib solver not working (hanging forever)

### ISSUE THREAD

**Issue by fteicht** [airbus/scikit-decide#281]
## 🐛 Bug

The [rllib solver example](https://github.com/airbus/scikit-decide/blob/master/examples/rllib_solver.py) hangs forever without any progression nor printed output on my system.
I get the following warning, but making the suggested change does not change anything:
`DeprecationWarning: rllib.agents::Trainer has been deprecated. Use rllib.algorithms::Algorithm instead. This will raise an error in the future!`

## To Reproduce

Run the following command: `python examples/rllib_solver.py`

## Expected behavior

The RLlib PPO agent starts training and eventually returns a policy which is tested by scikit-decide's `rollout` routine.

## Environment

```
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.27)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.12 (main, Jun 15 2023, 07:13:36) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-14.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] stable-baselines3==1.8.0
[pip3] torch==2.0.1
[conda] Could not collect

Skdecide version: Not available
```

**Comment by fteicht** [comment]
Digging into the issue, it turns out that the issue is due to `ray[tune]==2.2.0`'s `init` method that indefinitely hangs on my system.
More precisely, the following lines of code hang on my MacOS 14.1:
```
import ray
ray.init()
```

Installing `ray[tune]==2.8.0` solves the issue.
However, one should NOT install `ray[rllib]==2.8.0` with `scikit-decide` v0.9.7 because, then, it wants to install `gymnasium` instead of `gym`, which is not compatible with this version of `scikit-decide`.

Should we wait for `scikit-decide` to be compatible with `gymnasium` to solve this issue, or should we update the installation procedure to force the installation of `ray[tune]==2.8.0` AFTER having installed `ray[rllib]==2.2.0` ?

**Comment by nhuet** [comment]
To my mind, we are gymnasium-ready at an already ready [PR](https://github.com/airbus/scikit-decide/pull/276) (What a bunch of readiness!). So better to wait for this merge and the release to follow instead of having to do a lot of fixes everywhere (the gym0.21 install issues are generating lots of other issues). This means we should release very soon (as soon as PR 276 is merged).

**Comment by fteicht** [comment]
Makes sense, I agree with you!

**Comment by nhuet** [comment]
Could you check that it is now ok for you? @fteicht

**Comment by fteicht** [comment]
@nhuet Yes it's working for me now! Thanks a lot :-)
