### ISSUE TITLE
Build arm64 wheel on MacOs

### ISSUE THREAD

**Issue by fteicht** [airbus/scikit-decide#299]
## 🚀 Feature
Build arm64 wheel on MacOS but does not test it because we do not have a Cirrus account.

## Motivation

New MacBook Pro computers are natively using arm64 processors in their Mx chips. Providing arm64 wheels on MacOs will allow MacBook Pro users to install scikit-decide natively.

**Comment by nhuet** [comment]
Solved by #303.
