### ISSUE TITLE
Benchmark tutorial notebook returns errors

### ISSUE THREAD

**Issue by aralcimcim** [airbus/scikit-decide#311]
When running the benchmarking tutorial notebook at https://github.com/airbus/scikit-decide/blob/master/notebooks/14_benchmarking_tuto.ipynb on Colab, it returns multiple errors without finishing any of the simulations. The same also goes for running the notebook locally with a fresh Conda environment using Python 3.9. (Not posting any of the errors as it is the entire notebook)

**Comment by fteicht** [comment]
Hi @aralcimcim have you solved your issue? If so, can you please post here the solution? Thanks you!

**Comment by aralcimcim** [comment]
Hi @fteicht, thank you for replying. no have not yet solved my issue, did not have time to look again (that's why I closed it), I guess it is an issue with the Ray library and version updates. None of the benchmarks work, neither on Colab nor locally. I just needed the benchmark results of POMCP, so that I can save time before using it in my project.

**Comment by fteicht** [comment]
Which Operating System, python version and python packages are you using @aralcimcim ? Especially, are you using the latest version of scikit-decide (v0.9.8 as of today)?

**Comment by aralcimcim** [comment]
@fteicht Running Python 3.8.18 on Ubuntu, none of the algorithms run properly, code is from the example [Jupyter Notebook](https://github.com/airbus/scikit-decide/blob/master/notebooks/14_benchmarking_tuto.ipynb).

gymnasium: 0.28.1
ray: 2.9.1
scikit-decide: 0.9.8
stable-baselines3: 2.2.1

```
from stable_baselines3 import PPO  # this is a RL algorithm
analysis = tune.run(
    training_function,
    config={
        "solver": tune.grid_search(benchmark_solvers),
        "solver_args": {  # Optional
            # Example of how to customize specific solver arguments (if needed):
            "StableBaseline": {
                "algo_class": PPO,
                "baselines_policy": "MlpPolicy",
                "learn_config": {"total_timesteps": 1000},
            }
        },
    },
    raise_on_failed_trial=False,
    progress_reporter=tune.JupyterNotebookReporter(overwrite=True),
    # time_budget_s = 60
)

# Print (one of the) best solver, i.e. with maximum mean_episode_reward
best_config = analysis.get_best_config(metric="mean_episode_reward", mode="max")
print("==> Best solver:", best_config["solver"])
```

**Comment by aralcimcim** [comment]
Yes, it is working fine now. @neo-alex, @fteicht, this has been very helpful, thank you!
