### ISSUE TITLE
Scheduling Notebook

### ISSUE THREAD

**Issue by galleon** [airbus/scikit-decide#57]
## 📚 Documentation

This notebook will demonstrate how to use the scheduling API. It will:
  - explain the RCPSP problem
  - show how to create a simple one from scratch
  - show how to create one from a sm file
  - solve it using exact solver
  - show benefit of approximate solver in terms of resolution time

**Comment by fteicht** [comment]
Sounds good! Don't underestimate the potential code complexity of creating a RCPSP programmatically from scratch, maybe it is too many line codes for a notebook (maybe not => to check).
