### ISSUE TITLE
SGS policy methods and parameters

### ISSUE THREAD

**Issue by elcombato** [airbus/scikit-decide#62]
## 📚 Documentation

Further documentation needed for

- values of enumeration class [`BasePolicyMethod`](https://github.com/airbus/scikit-decide/blob/master/skdecide/hub/solver/sgs_policies/sgs_policies.py#L15)
- parameters of [`PolicyMethodParams`](https://github.com/airbus/scikit-decide/blob/master/skdecide/hub/solver/sgs_policies/sgs_policies.py#L25)

In particular the parameters `delta_time_freedom`, `delta_index_freedom` and their respective policy methods are unclear.

**Comment by g-poveda** [comment]
Solved at least partly in #357
