### ISSUE TITLE
RCPSP domain parameters

### ISSUE THREAD

**Issue by elcombato** [airbus/scikit-decide#63]
## 📚 Documentation

Parameters of the [RCPSP domain classes](https://github.com/airbus/scikit-decide/blob/master/skdecide/hub/domain/rcpsp/rcpsp_sk.py) are undocumented. In particular the meaning of the parameter [`max_horizon`](https://github.com/airbus/scikit-decide/blob/master/skdecide/hub/domain/rcpsp/rcpsp_sk.py#L27) is not obvious (whether its relevant during `solve` or during `rollout`).

**Comment by g-poveda** [comment]
See #357 #372
