### ISSUE TITLE
Nighly wheels generation 

### ISSUE THREAD

**Issue by galleon** [airbus/scikit-decide#77]
## 🚀 Feature
Modify/create action to generate nighlly wheels

## Motivation

New releases usually happen few times a year. It might be tedious for users to build themselves a release to benefit from new features. Having nightly releases would help close that gap.

## Pitch

- everyday at 1am (crontab) if `master` has changed  a release (set of wheels) is generated
- This set of wheels is released as a zip file
- The associated documentation is generated and published on GH pages under the dev tagname
- Only the latest 7 daily wheels are kept (but only the latest documentation is available online)

## Alternatives

Release more often :)

## Additional context

None

**Comment by dbarbier** [comment]
Another alternative: build wheels each time master is changed, which would not require a cron job.

Why keep 7 daily wheels?  A single one is enough in my opinion.

**Comment by dbarbier** [comment]
These wheels are not hosted on GH, why mimic them?  Unless there is a valid reason for keeping older wheels, the simplest solution is to only keep the latest one.

**Comment by galleon** [comment]
I would like to close this one. I need from @fteicht the strategy he would like to implement. I see two options between releases:
  1.  generate a new nightly wheels each time a PR is merged in `master` and keep them all - they are then all deleted when a new release is created
  2. generate a new nightly wheels each time a PR is merged in `master` and keep only the latest.
 
Both can be implemented. Option 2 is simpler from an end-user stand point since you don't have to choose a file (you will automatically  pick the latest one) a downside is that if it is buggy you cannot get back to the previous one,

Option 1 is a bit more difficult for the user in case of multiple nightlys between 2 releases.

Proposed name for the wheels is "nightly_YYYY-MM-DD_distance_hash.zip where:
 - YYY-MM-DD is the date at which the wheel is generated
 - distance is the number of commits since lastest release
 - hash is the hash from latest commit
 
 Option 1 or option 2 That is the question ?

**Comment by dbarbier** [comment]
Nightly wheels have been implemented, this issue can be closed.

**Comment by galleon** [comment]
Solved by #95 and #144
