### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by david1976** [airbus/scikit-decide#79]
## 🚀 Feature
how can I stop a process if it takes too long to solve the solution?

## Motivation

depending on the parameters set, sometimes it takes a few seconds and sometimes it does not end up giving a solution.

## Pitch

I would like to somehow be able to stop a process so that when I launch another one it doesn't run slow.

## Alternatives

Inglés (EE.UU.) 
Passing a timeout parameter with the time in seconds or some call for me to make the timeout and be able to stop the process

## Additional context

when you launch a process that takes a long time to return the solution and you ask for a different solution, the second process goes very slowly

**Comment by galleon** [comment]
@david1976  can you be more specific may be by providing an example because some of the solvers have already such a parameters. I need to understand which class of solvers you are using to better guide you.

**Comment by david1976** [comment]
@galleon i am working with MS Windows.

Thanks.

**Comment by nhuet** [comment]
Some solvers have already this kind of callback/watchdog. The issue #278 request to add it for all solvers.
